### ISSUE TITLE
add blocks dynamically

### ISSUE THREAD

**Issue by gregoriopellegrino** [fikrirasyid/woocommerce-newsletter-generator#2]
It would be very useful to be able to add blocks dynamically in preview mode: the number of products in the newsletter I'm working is variable.

**Comment by fikrirasyid** [comment]
I was thinking of enabling user to add blocks dynamically. However, considering:
1. This plugin was intentionally made for site admin who's confident with coding but avoid doing repetitive things
2. Custom blocks lead to other customization (layout, background, content width, etc). I wanted to keep the plugin simple.
3. It'll make the editing interface becomes too complicated

Hence, I took different approach instead: you can add your own template by creating add-on using `wc_newsletter_generator_templates` filter. For example:

```
add_filter( 'wc_newsletter_generator_templates', 'youraddon_register_wcng_templates' );     
function youraddon_register_wcng_templates( $templates ){
    // Register new templates
    $templates['youraddon-products'] = array(
        'name'                  => 'youraddon-products',
        'path'                  => plugin_dir_path( __FILE__ ) . 'templates/youraddon-products.php',
        'product_image_sizes'   => array( 
            array( 
                'id'        => 'wcng-product-thumb-youraddon', 
                'width'     => 160, 
                'height'    => 254, 
                'hard_crop' => true 
            ),
        )
    );

    return $templates;
}
```

You can see the template example on `woocommerce-newsletter-generator/templates`.

I hope it helps :)

**Comment by gregoriopellegrino** [comment]
Thank you, I'm already working on a template made by me.
