### ISSUE TITLE
PHP Fatal error: Call to undefined function get_current_screen()

### ISSUE THREAD

**Issue by gregoriopellegrino** [fikrirasyid/woocommerce-newsletter-generator#3]
Every time I open the newsletter editor in my PHP's error_log appear this line:

```
[error] PHP Fatal error: Call to undefined function get_current_screen() in wp-content/plugins/woocommerce-newsletter-generator-master/includes/class-wc-newsletter-generator-editor.php on line 56
```

**Comment by maxbmx** [comment]
Same here.

**Comment by gregoriopellegrino** [comment]
Fixed adding this line before line 56 in `wp-content/plugins/woocommerce-newsletter-generator-master/includes/class-wc-newsletter-generator-editor.php`

```
if ( ! function_exists( 'get_current_screen' ) ) return;
```

**Comment by maxbmx** [comment]
Have you pulled this change to the github? I don't see any new commits.

**Comment by gregoriopellegrino** [comment]
I've created the pull request
